### ISSUE TITLE
Send layers of struct over TCP, possible?

### ISSUE THREAD

**Issue by hubertcy** [liteserver/binn#17]
I have managed to send a simple struct over TCP.  Now, I am facing a new challenge. I need to send multiple layers of struct over TCP. Is that possible in C using your library? Multiple layers means struct A contains another struct B. Inside struct B, it contains struct C and so on.

**Comment by kroggen** [comment]
I guess you need to learn about JSON structures.

And check the Binn [usage](https://github.com/liteserver/binn/blob/master/usage.md#containers-inside-containers) documentation.
