### ISSUE TITLE
Using binn in C# possible?

### ISSUE THREAD

**Issue by hubertcy** [liteserver/binn#18]
I am looking for ways to use binn library in C# but could not get it to work by editing the header file like below (adding dll export). Any direction you can point me to?

__declspec(dllexport) ALWAYS_INLINE BOOL Binn_object_set_str(binn *obj, char *key, char *str) {
  return binn_object_set(obj, key, BINN_STRING, str, 0);
}

**Comment by kroggen** [comment]
You already created a question about C#. Stop creating duplicated questions.

Wait for someone that knows C# or learn the language by yourself.
