### ISSUE TITLE
build issue on mips32 (big endian)

### ISSUE THREAD

**Issue by biz122** [liteserver/binn#25]
Hey,

I did some test builds with various compilers for various architectures.

On mips 32 be (gcc), the compiler halts with "invalid operands to binary % (have ‘u16 * {aka short unsigned int *}’ and ‘int’)".

I think what you meant to do at line 76, 100, 126 in binn.c is a modulo operation on a pointer address rather than a pointer.

Like:
if (psource % 2 == 0)
if ((uintptr_t)psource % 2 == 0)

**Comment by kroggen** [comment]
Hi!

I updated the fix.

If you find any problem on big endian, please inform. I have no big endian processor here to test it.

Running the tests should be sufficient.

Thank you for your contribution!
