### ISSUE TITLE
Iterate over binn obj example

### ISSUE THREAD

**Issue by Mango-kid** [liteserver/binn#32]
I am having trouble understanding how to use `binn_object_foreach`. It would be great if someone could provide an example. I would like to be able to iterate through keys in the serialized data. 

Thanks.

**Comment by kroggen** [comment]
Hi!


You can check the [usage.md](https://github.com/liteserver/binn/blob/7b62ace826bd6c04ab03cdfa99be134e6abd44d2/usage.md#reading-sequentially-1)

There are many examples there.

If you still don't find something, feel comfortable to ask.

**Comment by Mango-kid** [comment]
Thanks, I didnt even see that doc, my mistake.
