### ISSUE TITLE
Contador no working??

### ISSUE THREAD

**Issue by hbiblia** [liteserver/binn#34]
![image](https://user-images.githubusercontent.com/1939353/91044644-9d713380-e5e3-11ea-8201-e2e46af39b9d.png)

Out:
**Contador: 1**

Estoy intentando hacer un contador pero no funciona... 
I'm trying to do a counter but it doesn't work ...

**Comment by kroggen** [comment]
Binn is intended to be used for serialization. We cannot update a value once it is serialized. You must store it elsewhere while you are willing to modify it, then use Binn only at the final moment when you want to serialize it to either save or transfer on network.

**Comment by hbiblia** [comment]
It would be nice if the data could be handled in real time. Thank you.
